on:
  workflow_call:
    inputs:

      PYTHON_QUALITY_DIR:
        description: "The relative dir in the repository where Python Quality Control is mounted as submodule"
        type: string
        required: true

      dbus-interface-lib:
        description: "Yes if the unit test for this repo requires dbus-interface-lib"
        type: boolean
        required: false
        default: false

      marvin-service:
        description: "Yes if the unit test for this repo requires marvin-service"
        type: boolean
        required: false
        default: false

      libPalantir:
        description: "Yes if the unit test for this repo requires libPalantir"
        type: boolean
        required: false
        default: false

      libSmeagol:
        description: "Yes if the unit test for this repo requires libSmeagol"
        type: boolean
        required: false
        default: false

      libCharon:
        description: "Yes if the unit test for this repo requires libCharon"
        type: boolean
        required: false
        default: false

      libLogger:
        description: "Yes if the unit test for this repo requires libLogger"
        type: boolean
        required: false
        default: false

      ultiLib:
        description: "Yes if the unit test for this repo requires ultiLib"
        type: boolean
        required: false
        default: false

jobs:
  PyTest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone dbus-interface-lib on default branch
        if: ${{ inputs.dbus-interface-lib }}
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/dbus-interface-lib
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: dbus-interface-lib
          fetch-depth: 0

      - name: Trying to checkout dbus-interface-lib on branch ${{ github.ref_name }}
        if: ${{ inputs.dbus-interface-lib }}
        continue-on-error: true
        run: |
          pwd
          ls -lha
          cd dbus-interface-lib
          pwd
          ls -lha
          git rev-parse --abbrev-ref HEAD
          git checkout ${{ github.ref_name }}
          git rev-parse --abbrev-ref HEAD
          
      - name: Checkout marvin-service for branch ${{ github.ref_name }}
        id: marvin-service
        if: ${{ inputs.marvin-service }}
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/marvin-service
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: marvin-service
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          
      - name: OPTIONAL Checkout marvin-service for the default branch
        if: ${{ inputs.marvin-service && steps.marvin-service.outcome == 'failure' }}
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/marvin-service
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: marvin-service
          fetch-depth: 0    

      - name: Checkout libPalantir for branch ${{ github.ref_name }}
        id: libPalantir
        if: ${{ inputs.libPalantir }}
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libPalantir
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libPalantir
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          
      - name: OPTIONAL Checkout libPalantir for the default branch
        if: ${{ inputs.libPalantir && steps.libPalantir.outcome == 'failure' }}
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libPalantir
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libPalantir
          fetch-depth: 0    

      - name: Checkout libSmeagol for branch ${{ github.ref_name }}
        id: libSmeagol
        if: ${{ inputs.libSmeagol }}
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libSmeagol
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libSmeagol
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          
      - name: OPTIONAL Checkout libSmeagol for the default branch
        if: ${{ inputs.libSmeagol && steps.libSmeagol.outcome == 'failure' }}
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libSmeagol
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libSmeagol
          fetch-depth: 0    

      - name: Checkout libCharon for branch ${{ github.ref_name }}
        id: libCharon
        if: ${{ inputs.libCharon }}
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libCharon
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libCharon
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          
      - name: OPTIONAL Checkout libCharon for the default branch
        if: ${{ inputs.libCharon && steps.libCharon.outcome == 'failure' }}
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libCharon
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libCharon
          fetch-depth: 0    

      - name: Checkout libLogger for branch ${{ github.ref_name }}
        id: libLogger
        if: ${{ inputs.libLogger }}
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libLogger
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libLogger
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          
      - name: OPTIONAL Checkout libLogger for the default branch
        if: ${{ inputs.libLogger && steps.libLogger.outcome == 'failure' }}
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/libLogger
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: libLogger
          fetch-depth: 0    

      - name: Checkout ultiLib for branch ${{ github.ref_name }}
        id: ultiLib
        if: ${{ inputs.ultiLib }}
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/ultiLib
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: ultiLib
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          
      - name: OPTIONAL Checkout ultiLib for the default branch
        if: ${{ inputs.ultiLib && steps.ultiLib.outcome == 'failure' }}
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/ultiLib
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          path: ultiLib
          fetch-depth: 0    

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ULTIMAKER_CI_PAT }}
          submodules: recursive
          path: repo_under_test

      - name: PyTest
        run: |
          pwd
          ls -lha
          cd repo_under_test
          source ./docker_env/make_docker.sh ""
          run_in_docker "./${{ inputs.PYTHON_QUALITY_DIR }}/run_pytest.sh"

      - name: Dump GitHub context
        if: ${{ always() }}
        env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
           JOB_CONTEXT: ${{ toJson(job) }}
           STEPS_CONTEXT: ${{ toJson(steps) }}
           RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "${GITHUB_CONTEXT}"
          echo "${JOB_CONTEXT}"
          echo "${STEPS_CONTEXT}"
          echo "${RUNNER_CONTEXT}"
          
